from django.urls import path
from . import views

urlpatterns = [
    path("signup/", views.signup),
    path("login/", views.login),
    path("logout/", views.logout),
    path("verify/", views.verify_view),
    path('current-user/', views.current_user),
    path('profile/', views.get_user_profile, name='get_user_profile'),
    path('update-user/', views.update_user),
    path('update-online-status/', views.update_online_status),
    path('user-status/<str:user_id>/', views.get_user_online_status),
    path('update-last-seen/', views.update_last_seen),
    path('inactive-users/', views.get_inactive_users),
    path("send-otp/", views.send_otp, name="send-otp"),
    path("verify-otp/", views.verify_otp, name="verify-otp"),
    path("send-verification-code/", views.send_verification_code, name="send-verification-code"),
    path("verify-phone/", views.verify_phone, name="verify-phone"),
    path('user/survey/<str:user_id>/', views.save_survey_answers),
    path('category/', views.add_category),
    path('speciality/', views.add_speciality),
    path('categories-with-specialities/', views.get_category_with_speciality),
    path('get-skills/', views.get_skills),
    path('add-skill/', views.add_skill),
    path('update-skill/<str:id>/', views.update_skill),
    path('delete-skill/<str:id>/', views.delete_skill),
    
    path("upload-resume/", views.upload_resume, name="upload-resume"),
    path('resumes/<str:id>/', views.get_resume),
    path('save-specialities/', views.save_specialities),
    path('save-title/', views.save_title),
    path('add-experience/', views.add_experience),
    path('update-experience/<str:experience_id>/', views.update_experience),
    path('get-work-experiences/<str:user_id>/', views.get_work_experiences),
    path('delete-experience/<str:experience_id>/<str:user_id>/', views.delete_experience),
    path('get-experience/<str:id>/', views.get_experience_by_id),
    path('add-language/', views.add_language),
    path('add-skills/', views.add_skills_to_requests),
    path('add-biography/', views.add_biography),
    path('add-hourlyrate/', views.add_hourly_rate),
    path('add-photo-location-details/', views.add_photo_location),
    path('add-company-details/', views.add_company_details, name='add_company_details'),
    path('company-details/<str:user_id>/', views.get_company_details, name='get_company_details'),
    path("upload-photo/", views.add_photograph, name="add-photograph"),
    path("add-video-introduction/", views.add_video_introduction, name="add-video-introduction"),
    path("profile/submit-application-for-review/", views.submit_for_review, name="submit-for-review"),
    path('profile/<str:user_id>/', views.get_profile_details, name='get_profile_details'),
    path('add-education/', views.add_education, name='add_education'),
    path('update-education/<str:education_id>/', views.update_education, name='update_education'),
    path('get-educations/<str:user_id>/', views.get_educations, name='get_educations'),
    path('delete-education/<str:education_id>/<str:user_id>/', views.delete_education, name='delete_education'),
    path('education/single/<str:education_id>/', views.get_education_by_id, name='get_education_by_id'),
    path('add-other-experience/', views.add_other_experience, name='add_other_experience'),
    path('update-other-experience/<str:other_experience_id>/', views.update_other_experience, name='update_other_experience'),
    path('delete-other-experience/<str:other_experience_id>/<str:user_id>/', views.delete_other_experience, name='delete_other_experience'),
    path('get-other-experiences/<str:user_id>/', views.get_other_experiences, name='get_other_experiences'),
    path('check-request-status/', views.check_request_status, name='check_request_status'),

    path('add-job-post-title/', views.add_job_post_title, name='add_job_post_title'),
    path('add-job-scope-details/', views.add_job_scope, name='add_job_scope'),
    path('add-job-budget/', views.add_job_budget, name='add_job_budget'),
    path("upload-attachments/", views.upload_job_post_attachment, name="upload_job_post_attachment"),
    path("jobpost/send-verification-email/", views.send_verification_email, name="send_verification_email"),
    path("jobposts/attachments/<str:id>/", views.get_job_attachment, name="get_job_attachment"),
    path('jobpost/<str:job_id>/', views.get_job_post_details, name='get_job_post_details'),
    path('jobposts/draft/', views.get_draft_job_post_id, name='get_draft_job_post_id'),
    path('add-jobpost-skills/', views.add_job_post_skills, name='add_job_post_skills'),
    path('verify-email/jobpost/<str:job_id>/', views.verify_job_post_email, name='verify_job_post_email'),
    path('jobposts/fetch/', views.fetch_job_posts, name='fetch_job_posts'),
    path('jobposts/client/<str:user_id>/', views.fetch_job_posts_for_client, name='fetch_job_posts_for_client'),
    path('jobposts/fetchJobById/', views.fetch_job_post_by_id, name='fetch_job_post_by_id'),
    path('jobproposals/create/', views.create_job_proposal, name='create_job_proposal'),
    path('jobproposals/job/<str:job_id>/', views.fetch_proposals_for_job, name='fetch_proposals_for_job'),
    path('jobproposalsbyid/fetch/', views.get_job_proposal_details_by_id, name='get_job_proposal_details_by_id'),
    path('jobproposals/attachments/<str:id>/', views.get_job_proposal_attachment, name='get_job_proposal_attachment'),
    path('freelancer/summary/<str:user_id>/', views.get_freelancer_summary, name='get_freelancer_summary'),
    path('freelancer/profile/<str:user_id>/', views.get_freelancer_profile),
    path('client/profile/<str:user_id>/', views.get_client_profile),
    path('client/profile-details/<str:user_id>/', views.get_client_profile_details, name='get_client_profile_details'),
    
    # Password Management
    path('change-password/', views.change_password, name='change_password'),
    
    # Profile Settings
    path('profile-settings/', views.get_profile_settings, name='get_profile_settings'),
    path('update-profile-settings/', views.update_profile_settings, name='update_profile_settings'),
    
    # Client Profile Settings
    path('client-profile-settings/', views.get_client_profile_settings, name='get_client_profile_settings'),
    path('update-client-profile-settings/', views.update_client_profile_settings, name='update_client_profile_settings'),
    
    # Payment Card 
    path('payment-cards/', views.get_payment_cards, name='get_payment_cards'),
    path('payment-cards/add/', views.add_payment_card, name='add_payment_card'),
    path('payment-cards/<str:card_id>/', views.update_payment_card, name='update_payment_card'),
    path('payment-cards/<str:card_id>/delete/', views.delete_payment_card, name='delete_payment_card'),
    path('payment-cards/<str:card_id>/set-default/', views.set_default_payment_card, name='set_default_payment_card'),
    
    # PayPal
    path('paypal-accounts/', views.get_paypal_accounts, name='get_paypal_accounts'),
    path('paypal-accounts/add/', views.add_paypal_account, name='add_paypal_account'),
    path('paypal-accounts/<str:account_id>/', views.update_paypal_account, name='update_paypal_account'),
    path('paypal-accounts/<str:account_id>/delete/', views.delete_paypal_account, name='delete_paypal_account'),
    path('paypal-accounts/<str:account_id>/set-default/', views.set_default_paypal_account, name='set_default_paypal_account'),
    path('paypal/payment/initiate/', views.initiate_paypal_payment, name='initiate_paypal_payment'),
    path('paypal/payment/complete/', views.complete_paypal_payment, name='complete_paypal_payment'),
    
    path('jobpost/publish/<str:job_id>/', views.publish_job_post, name='publish_job_post'),
]
